apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-test-hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: teste
        image: apine:latest
        command:
          - ["sleep", "20"]
      restartPolicy: Never
  backoffLimit: 2