{{ - if .Values.argo.tests.enabled - }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-test-hook-post-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: testePost
        image: bash
        command:
          - "sleep"
          - "20"
      restartPolicy: Never
  backoffLimit: 2
{{- end -}}