apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-test-hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
      - name: teste
        image: bash
        command:
          - "sleep"
          - "20"
      restartPolicy: Never
  backoffLimit: 2